package core

type Response struct {
	StatusCode int
	Headers    map[string]string

	// Body is used to get response body from controller function in any type
	Body interface{}

	// RawBody is generated by the api-core from the Body if returned by the controller
	RawBody         string
	IsBase64Encoded bool
}
